<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="NuGet.Versioning" Version="7.9.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="TextCopy" Version="6.2.1" />
  </ItemGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>
</Project>
